name: scouting_qr_maker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  orbit_standard_library: ^0.2.0
  package_info_plus: ^8.3.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  qr_code_scanner_plus: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
